version: '3.8'

services:

  fastapi_app:

    build:

      context: .

      dockerfile: Dockerfile

    container_name: fastapi_app

    ports:

      - "8000:8000"


    restart: always


  nginx:

    image: nginx:latest

    container_name: nginx

    ports:

      - "80:80"

    volumes:

      - ./fastapi.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:

      - fastapi_app

    restart: always

