name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2 Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            
            cd /home/ubuntu
            cd fastapi-book-project
            git fetch origin main   # Pull the latest changes from the repo
            git reset --hard origin main  # Discard local changes
            docker-compose down --remove-orphans
            docker-compose build --no-cache  # Rebuild the image without cache
            docker-compose up -d --force-recreate --build  # Recreate containers with the new build

